cd /mnt/c/Users/sleblanc/Research/python_codes
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170831starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170831_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170903starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170903_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170904starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170904_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170905starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170905_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170906starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170906_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170908starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170908_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170909starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170909_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170912starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170912_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170916starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170916_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170917starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20160917_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170918starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170918_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170919starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170919_zen_cld_retrieved.mat
python Run_zen_cld_retrieval.py --noretrieval -o /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/ -lut /mnt/c/Users/sleblanc/Research/ORACLES/model/v5_80aod_ORACLES_lut.mat -liq -plotlut -refrange 2 25 -taurange 1 60 /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/4STARB_20170920starzen.mat /mnt/c/Users/sleblanc/Research/NAAMES/starzen/naames3/20170920_zen_cld_retrieved.mat
